=head1 NAME

Roto2Oto - Generate UTAU oto configuration from RUCE Roto configuration.

=head1 SYNOPSIS

roto2oto [Options] rotofile

=head1 OPTIONS

=head2 Other

B<-V>

    Verbose.

    Default: disabled

B<-v>

    Print version.

    Default: disabled

=head1 VERSION

Roto2Oto 1.0.0.1

=head1 LICENSE

Rocaloid Toolchain is released under GPLv3.

=head1 AUTHOR

Hua Kanru(sleepwalking(at)rocaloid.org)

